In [33]:
import torch 
del print

In [34]:
data = [[1,2],[3,4]] #python list,not tensor yet
x_data = torch.tensor(data) #converting list into pytorch tensor
print("Tensor from List:\n", x_data)


Tensor from List:
 tensor([[1, 2],
        [3, 4]])


In [35]:
x_ran = torch.rand(2,3)
print("\n Random Tensors:\n", x_ran)



 Random Tensors:
 tensor([[0.1919, 0.0709, 0.4477],
        [0.1627, 0.2184, 0.6915]])


In [36]:
x_zeros = torch.zeros(2,3)
print("\n Zero Number:\n", x_zeros)



 Zero Number:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [37]:
x_like = torch.ones_like(x_data)
print("\n Ones like x_data:\n", x_like)



 Ones like x_data:
 tensor([[1, 1],
        [1, 1]])


In [38]:
x_float = torch.tensor([1.0,2.0,3.0], dtype=torch.float32)
print("\n Float tensors:\n", x_float)



 Float tensors:
 tensor([1., 2., 3.])


In [39]:
print("\n shape:" ,x_data.shape)
print("\n Data Type:" ,x_data.dtype)
print("\n Device:" ,x_data.device)


 shape: torch.Size([2, 2])

 Data Type: torch.int64

 Device: cpu


In [40]:
x = torch.tensor([[1,2],[3,4]])

In [41]:
y = torch.tensor([[5,6],[7,8]])

In [42]:
print("x+y = \n", x+y)

x+y = 
 tensor([[ 6,  8],
        [10, 12]])


In [43]:
#MATRIX MULTIPLICATION,T means transpose
print("x @y.T = \n", x@y.T) 

x @y.T = 
 tensor([[17, 23],
        [39, 53]])


In [44]:
#ElEMENT WISE MULTIPLICATION
print("x * y = \n", x * y) 

x * y = 
 tensor([[ 5, 12],
        [21, 32]])


In [45]:
reshaped = x.view(4)
print("Reshaped x (1D) \n" ,reshaped)

Reshaped x (1D) 
 tensor([1, 2, 3, 4])


In [46]:
#indexing
print("First row of x:" , x[0])

First row of x: tensor([1, 2])


In [47]:
#slicing
print ("Element at [1,1]:", x[1,1])

Element at [1,1]: tensor(4)


In [48]:
x_ran1 = torch.rand(3,3)
print("\n Random tensors\n" , x_ran1)


 Random tensors
 tensor([[0.8426, 0.0604, 0.3191],
        [0.3962, 0.0073, 0.6938],
        [0.8880, 0.6416, 0.5640]])


In [49]:
print("\n Transpose of Random Tensors\n" ,x_ran1.T)


 Transpose of Random Tensors
 tensor([[0.8426, 0.3962, 0.8880],
        [0.0604, 0.0073, 0.6416],
        [0.3191, 0.6938, 0.5640]])


In [50]:
print("\n Matrix multiplication with itself \n" ,x_ran1 @ x_ran1.T)


 Matrix multiplication with itself 
 tensor([[0.8155, 0.5557, 0.9670],
        [0.5557, 0.6383, 0.7478],
        [0.9670, 0.7478, 1.5184]])
